### PR TITLE
Fix building with musl

### LINKED ISSUE #33: tracepath and ping fail to compile with musl-libc and linux-headers 4.2.0
Ran into this while cross compiling for musl. Will check to see if it works fine natively once I can.

```
make -j4 CC="x86_64-pc-linux-musl-cc" CFLAGS="-march=native -pipe -Os -g" LIBC_INCLUDE="/usr/x86_64-pc-linux-musl/include" USE_CAP=no USE_GCRYPT=no USE_IDN=no USE_NETTLE=no
fatal: Not a git repository (or any of the parent directories): .git
x86_64-pc-linux-musl-cc -march=native -pipe -Os -g -march=native -pipe -Os -g -D_GNU_SOURCE  -c ping.c    -o ping.o
x86_64-pc-linux-musl-cc -march=native -pipe -Os -g -march=native -pipe -Os -g -D_GNU_SOURCE  -c ping_common.c   -o ping_common.o
x86_64-pc-linux-musl-cc -march=native -pipe -Os -g -march=native -pipe -Os -g -D_GNU_SOURCE  -c ping6_common.c   -o ping6_common.o
x86_64-pc-linux-musl-cc -march=native -pipe -Os -g -march=native -pipe -Os -g -D_GNU_SOURCE  -c tracepath.c  -o tracepath.o
In file included from tracepath.c:17:0:
/usr/x86_64-pc-linux-musl/include/linux/errqueue.h:33:18: error: array type has incomplete element type 'struct timespec'
  struct timespec ts[3];
                  ^
Makefile:137: recipe for target 'tracepath.o' failed
make: *** [tracepath.o] Error 1
make: *** Waiting for unfinished jobs....
ping.c: In function 'main':
ping.c:289:22: error: 'SCOPE_DELIMITER' undeclared (first use in this function)
     p = strchr(addr, SCOPE_DELIMITER);
                      ^
ping.c:289:22: note: each undeclared identifier is reported only once for each function it appears in
Makefile:137: recipe for target 'ping.o' failed
make: *** [ping.o] Error 1
```

### PR DESCRIPTION
**Pull request by somasis**
This fixes #33. I can confirm it also builds fine on glibc.

### CODE REVIEW

**Comment by okias** [comment]
Thank you!
